spring:
  application:
    name: spring-transaction
  jpa:
    #    database-platform: org.hibernate.dialect.MySQLDialect  # 예시: (MySQL 8.x용) 방언 설정
    hibernate:
      ddl-auto: update
    show-sql: true  # SQL 출력 여부
    properties:
      hibernate:
        lock:
          timeout: 5000   # 5초 대기 후 타임아웃 발생
        format_sql: true  # SQL을 보기 좋게 포맷팅할지 여부
        use_sql_comments: true  # SQL에 주석을 추가할지 여부
        highlight_sql: true  # 쿼리에서 SQL 키워드를 하이라이트할지 여부 (Hibernate 5.4 이상에서 가능)
#        generate_statistics: true  # Hibernate 통계를 생성할지 여부


logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE  # JDBC 바인딩 로그 레벨 설정
        SQL: INFO # SQL 쿼리 로그 레벨 설정
        transaction: TRACE # 트랜잭션 로그 레벨 설정

    org.springframework.transaction: TRACE  # 트랜잭션 관리에 대한 로그
    org.springframework.transaction.interceptor: TRACE  # 트랜잭션 인터셉터 관련 로그
    org.springframework.transaction.support.TransactionSynchronizationManager: TRACE  # 트랜잭션 동기화 관련 로그
    org.springframework.orm.jpa.JpaTransactionManager: TRACE  # JPA 트랜잭션 매니저 로그
